"use client";

// import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import NavBar from "@/components/common/NavBar";
import styled from "styled-components";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>BrandFocusGroup</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/favicon.ico" />
      </head>
      <LayoutStyled>
        <header className="sidebar">
          <NavBar />
        </header>
        <body className="content">{children}</body>
      </LayoutStyled>
    </html>
  );
}

const HEADER_HEIGHT = 80;

const LayoutStyled = styled.section`
  display: grid;
  grid-template-columns: minmax(0, 300px) auto;
  grid-template-rows: auto 1fr;
  grid-template-areas:
    "header header"
    "sidebar content";
  height: 100vh;
  overflow: hidden;
  font-size: 18px;
  transition: font-size 0.25s linear;
  @media (max-width: 500px) {
    display: block;
  }

  .headerbar {
    grid-area: header;
    grid-column: 1 / 3;
    grid-row: 1 / 2;
    height: ${HEADER_HEIGHT}px;
  }

  .sidebar {
    grid-area: sidebar;
    grid-column: 1 / 2;
    height: calc(100vh - ${HEADER_HEIGHT}px);
  }

  .content {
    grid-area: content;
    grid-column: 2 / 3;
    grid-row: 2 / 3;
    height: calc(100vh - ${HEADER_HEIGHT}px);
    padding: 20px;
    overflow-x: hidden;
    overflow-y: auto;
  }
`;
