"use client";

import Footer from "@/components/common/footer";
// import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import NavBar from "@/components/common/NavBar";
import styled from "styled-components";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>BrandFocusGroup</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/favicon.ico" />
      </head>
      <header>
        <NavBar />
      </header>
      <body className="content">{children}</body>
      <Footer />
    </html>
  );
}
